std_msgs/Header header
# <- type
#               ^ variable

bool manual
# <- type.builtin
#    ^ variable
string mode
# <- type.builtin
#      ^ variable
uint8 status
# <- type.builtin
#     ^ variable

string MODE_SIMPLE = SIMPLE
# <- type.builtin
#      ^ constant
#                  ^ operator
#                    ^ string
string MODE_ADVANCED = ADVANCED
# <- type.builtin
#      ^ constant
#                    ^ operator
#                      ^ string
string MODE_SUPER_ADVANCED = SUPER_ADVANCED
# <- type.builtin
#      ^ constant
#                          ^ operator
#                            ^ string
