/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_separator = 1,
  anon_sym_EQ = 2,
  sym_identifier = 3,
  sym_const_identifier = 4,
  sym_custom_type = 5,
  sym_package_specifier = 6,
  anon_sym_bool = 7,
  anon_sym_byte = 8,
  anon_sym_char = 9,
  aux_sym_primitive_type_token1 = 10,
  aux_sym_primitive_type_token2 = 11,
  anon_sym_duration = 12,
  anon_sym_time = 13,
  aux_sym_string_type_token1 = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_POUND = 18,
  aux_sym_comment_token1 = 19,
  aux_sym_string_token1 = 20,
  aux_sym_string_token2 = 21,
  sym__decimal_integer = 22,
  sym__binary_integer = 23,
  sym__hexadecimal_integer = 24,
  sym__octal_integer = 25,
  aux_sym_float_token1 = 26,
  aux_sym_float_token2 = 27,
  anon_sym_True = 28,
  anon_sym_true = 29,
  anon_sym_False = 30,
  anon_sym_false = 31,
  anon_sym_COMMA = 32,
  sym_source_file = 33,
  sym_service = 34,
  sym_action = 35,
  sym__statement = 36,
  sym_field = 37,
  sym_constant = 38,
  sym_field_default = 39,
  sym__type = 40,
  sym__base_type = 41,
  sym_external_custom_type = 42,
  sym_primitive_type = 43,
  sym_string_type = 44,
  sym_array = 45,
  sym_comment = 46,
  sym_value = 47,
  sym_primitive_value = 48,
  sym_string = 49,
  sym_integer = 50,
  sym_float = 51,
  sym_bool = 52,
  sym_array_value = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_array_value_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_separator] = "separator",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_const_identifier] = "const_identifier",
  [sym_custom_type] = "custom_type",
  [sym_package_specifier] = "package_specifier",
  [anon_sym_bool] = "bool",
  [anon_sym_byte] = "byte",
  [anon_sym_char] = "char",
  [aux_sym_primitive_type_token1] = "primitive_type_token1",
  [aux_sym_primitive_type_token2] = "primitive_type_token2",
  [anon_sym_duration] = "duration",
  [anon_sym_time] = "time",
  [aux_sym_string_type_token1] = "string_type_token1",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym__decimal_integer] = "_decimal_integer",
  [sym__binary_integer] = "_binary_integer",
  [sym__hexadecimal_integer] = "_hexadecimal_integer",
  [sym__octal_integer] = "_octal_integer",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [anon_sym_True] = "True",
  [anon_sym_true] = "true",
  [anon_sym_False] = "False",
  [anon_sym_false] = "false",
  [anon_sym_COMMA] = ",",
  [sym_source_file] = "source_file",
  [sym_service] = "service",
  [sym_action] = "action",
  [sym__statement] = "_statement",
  [sym_field] = "field",
  [sym_constant] = "constant",
  [sym_field_default] = "field_default",
  [sym__type] = "_type",
  [sym__base_type] = "_base_type",
  [sym_external_custom_type] = "external_custom_type",
  [sym_primitive_type] = "primitive_type",
  [sym_string_type] = "string_type",
  [sym_array] = "array",
  [sym_comment] = "comment",
  [sym_value] = "value",
  [sym_primitive_value] = "primitive_value",
  [sym_string] = "string",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_bool] = "bool",
  [sym_array_value] = "array_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_value_repeat1] = "array_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_separator] = sym_separator,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_const_identifier] = sym_const_identifier,
  [sym_custom_type] = sym_custom_type,
  [sym_package_specifier] = sym_package_specifier,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_byte] = anon_sym_byte,
  [anon_sym_char] = anon_sym_char,
  [aux_sym_primitive_type_token1] = aux_sym_primitive_type_token1,
  [aux_sym_primitive_type_token2] = aux_sym_primitive_type_token2,
  [anon_sym_duration] = anon_sym_duration,
  [anon_sym_time] = anon_sym_time,
  [aux_sym_string_type_token1] = aux_sym_string_type_token1,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym__decimal_integer] = sym__decimal_integer,
  [sym__binary_integer] = sym__binary_integer,
  [sym__hexadecimal_integer] = sym__hexadecimal_integer,
  [sym__octal_integer] = sym__octal_integer,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [anon_sym_True] = anon_sym_True,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_False] = anon_sym_False,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_source_file] = sym_source_file,
  [sym_service] = sym_service,
  [sym_action] = sym_action,
  [sym__statement] = sym__statement,
  [sym_field] = sym_field,
  [sym_constant] = sym_constant,
  [sym_field_default] = sym_field_default,
  [sym__type] = sym__type,
  [sym__base_type] = sym__base_type,
  [sym_external_custom_type] = sym_external_custom_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_string_type] = sym_string_type,
  [sym_array] = sym_array,
  [sym_comment] = sym_comment,
  [sym_value] = sym_value,
  [sym_primitive_value] = sym_primitive_value,
  [sym_string] = sym_string,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_bool] = sym_bool,
  [sym_array_value] = sym_array_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_value_repeat1] = aux_sym_array_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_const_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_custom_type] = {
    .visible = true,
    .named = true,
  },
  [sym_package_specifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_byte] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_primitive_type_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_primitive_type_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_duration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__decimal_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__binary_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__hexadecimal_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__octal_integer] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_True] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_False] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_field_default] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__base_type] = {
    .visible = false,
    .named = true,
  },
  [sym_external_custom_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_string_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_array_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_default = 1,
  field_feedback = 2,
  field_goal = 3,
  field_message = 4,
  field_name = 5,
  field_request = 6,
  field_response = 7,
  field_result = 8,
  field_type = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
  [field_feedback] = "feedback",
  [field_goal] = "goal",
  [field_message] = "message",
  [field_name] = "name",
  [field_request] = "request",
  [field_response] = "response",
  [field_result] = "result",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 3},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 2},
  [14] = {.index = 22, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_message, 0},
  [1] =
    {field_response, 1},
  [2] =
    {field_name, 1},
    {field_type, 0},
  [4] =
    {field_request, 0},
  [5] =
    {field_feedback, 2},
  [6] =
    {field_result, 1},
  [7] =
    {field_default, 2},
    {field_name, 1},
    {field_type, 0},
  [10] =
    {field_goal, 0},
  [11] =
    {field_request, 0},
    {field_response, 2},
  [13] =
    {field_feedback, 3},
    {field_result, 1},
  [15] =
    {field_name, 1},
    {field_type, 0},
    {field_value, 3},
  [18] =
    {field_feedback, 3},
    {field_goal, 0},
  [20] =
    {field_goal, 0},
    {field_result, 2},
  [22] =
    {field_feedback, 4},
    {field_goal, 0},
    {field_result, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 25,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(86);
      ADVANCE_MAP(
        '"', 2,
        '#', 114,
        '\'', 5,
        '+', 56,
        ',', 140,
        '-', 7,
        '0', 122,
        '<', 58,
        '=', 88,
        'F', 90,
        'T', 91,
        '[', 112,
        ']', 113,
        '_', 125,
        'b', 39,
        'c', 26,
        'd', 53,
        'f', 17,
        'i', 38,
        's', 51,
        't', 28,
        'u', 27,
        'w', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 114,
        '\'', 5,
        '0', 122,
        'F', 59,
        'T', 67,
        ']', 113,
        '_', 125,
        'f', 60,
        't', 68,
        '+', 56,
        '-', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(118);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(119);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(114);
      if (lookahead == ',') ADVANCE(140);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '[') ADVANCE(112);
      if (lookahead == ']') ADVANCE(113);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(93);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(120);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(121);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '0') ADVANCE(122);
      if (lookahead == '_') ADVANCE(125);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '0') ADVANCE(124);
      if (('1' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(87);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '1') ADVANCE(16);
      if (lookahead == '3') ADVANCE(11);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == '8') ADVANCE(107);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '2') ADVANCE(107);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '2') ADVANCE(106);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(15);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '4') ADVANCE(107);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '4') ADVANCE(106);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 16:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '6') ADVANCE(107);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 17:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 18:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 19:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'e') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'e') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'e') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 24:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'e') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 25:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'g') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 26:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'h') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 28:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 30:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 31:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'i') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'l') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 33:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'l') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 35:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'm') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 36:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'n') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 37:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'n') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'n') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(40);
      if (lookahead == 'y') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 40:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 44:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 46:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 's') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 47:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 's') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 48:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 't') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 't') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 't') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 51:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 't') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 't') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 53:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'u') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 54:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 55:
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      if (lookahead == '0') ADVANCE(122);
      if (lookahead == '_') ADVANCE(125);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 57:
      if (lookahead == '0') ADVANCE(124);
      if (('1' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(125);
      END_STATE();
    case 58:
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 60:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 66:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 69:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 70:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 71:
      if (lookahead == 'u') ADVANCE(61);
      END_STATE();
    case 72:
      if (lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 73:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 74:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 75:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(126);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(128);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(127);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(93);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 84:
      if (eof) ADVANCE(86);
      ADVANCE_MAP(
        '"', 2,
        '#', 114,
        '\'', 5,
        '+', 56,
        '-', 7,
        '0', 122,
        'F', 94,
        'T', 98,
        '[', 112,
        '_', 125,
        'b', 39,
        'c', 26,
        'd', 53,
        'f', 17,
        'i', 38,
        's', 51,
        't', 28,
        'u', 27,
        'w', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(84);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(101);
      END_STATE();
    case 85:
      if (eof) ADVANCE(86);
      ADVANCE_MAP(
        '#', 114,
        '+', 57,
        ',', 140,
        '-', 8,
        '0', 124,
        '<', 58,
        ']', 113,
        'b', 39,
        'c', 26,
        'd', 53,
        'f', 34,
        'i', 38,
        's', 51,
        't', 29,
        'u', 27,
        'w', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(85);
      if (('1' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(125);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(101);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_const_identifier);
      if (lookahead == '_') ADVANCE(81);
      if (lookahead == 'a') ADVANCE(97);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_const_identifier);
      if (lookahead == '_') ADVANCE(81);
      if (lookahead == 'r') ADVANCE(100);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_const_identifier);
      if (lookahead == '_') ADVANCE(81);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_const_identifier);
      if (lookahead == '_') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'a') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'e') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'e') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'l') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'r') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 's') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_custom_type);
      if (lookahead == 'u') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_custom_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_package_specifier);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_bool);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_byte);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_char);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_primitive_type_token1);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_primitive_type_token2);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_duration);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_time);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_string_type_token1);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(115);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(117);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(118);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(120);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym__decimal_integer);
      ADVANCE_MAP(
        '.', 77,
        '_', 125,
        'B', 75,
        'b', 75,
        'E', 73,
        'e', 73,
        'O', 76,
        'o', 76,
        'X', 80,
        'x', 80,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (lookahead == '.') ADVANCE(77);
      if (lookahead == '_') ADVANCE(125);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(75);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(76);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym__binary_integer);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym__hexadecimal_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym__octal_integer);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_True);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_True);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_False);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_False);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '_') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 85},
  [2] = {.lex_state = 84},
  [3] = {.lex_state = 85},
  [4] = {.lex_state = 85},
  [5] = {.lex_state = 85},
  [6] = {.lex_state = 85},
  [7] = {.lex_state = 85},
  [8] = {.lex_state = 85},
  [9] = {.lex_state = 85},
  [10] = {.lex_state = 85},
  [11] = {.lex_state = 85},
  [12] = {.lex_state = 85},
  [13] = {.lex_state = 85},
  [14] = {.lex_state = 85},
  [15] = {.lex_state = 85},
  [16] = {.lex_state = 85},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 85},
  [22] = {.lex_state = 85},
  [23] = {.lex_state = 85},
  [24] = {.lex_state = 85},
  [25] = {.lex_state = 85},
  [26] = {.lex_state = 85},
  [27] = {.lex_state = 85},
  [28] = {.lex_state = 85},
  [29] = {.lex_state = 85},
  [30] = {.lex_state = 85},
  [31] = {.lex_state = 85},
  [32] = {.lex_state = 85},
  [33] = {.lex_state = 85},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 85},
  [36] = {.lex_state = 85},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 85},
  [39] = {.lex_state = 85},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 85},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 116},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_const_identifier] = ACTIONS(1),
    [sym_custom_type] = ACTIONS(1),
    [sym_package_specifier] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_byte] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [aux_sym_primitive_type_token1] = ACTIONS(1),
    [aux_sym_primitive_type_token2] = ACTIONS(1),
    [anon_sym_duration] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [aux_sym_string_type_token1] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym__decimal_integer] = ACTIONS(1),
    [sym__binary_integer] = ACTIONS(1),
    [sym__hexadecimal_integer] = ACTIONS(1),
    [sym__octal_integer] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [anon_sym_True] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_False] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym_service] = STATE(54),
    [sym_action] = STATE(54),
    [sym__statement] = STATE(26),
    [sym_field] = STATE(32),
    [sym_constant] = STATE(32),
    [sym__type] = STATE(55),
    [sym__base_type] = STATE(41),
    [sym_external_custom_type] = STATE(48),
    [sym_primitive_type] = STATE(43),
    [sym_string_type] = STATE(42),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_separator] = ACTIONS(7),
    [sym_custom_type] = ACTIONS(9),
    [sym_package_specifier] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_byte] = ACTIONS(13),
    [anon_sym_char] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [aux_sym_primitive_type_token2] = ACTIONS(13),
    [anon_sym_duration] = ACTIONS(13),
    [anon_sym_time] = ACTIONS(13),
    [aux_sym_string_type_token1] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_field_default] = STATE(27),
    [sym_comment] = STATE(2),
    [sym_value] = STATE(28),
    [sym_primitive_value] = STATE(29),
    [sym_string] = STATE(24),
    [sym_integer] = STATE(24),
    [sym_float] = STATE(24),
    [sym_bool] = STATE(24),
    [sym_array_value] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_separator] = ACTIONS(17),
    [sym_custom_type] = ACTIONS(19),
    [sym_package_specifier] = ACTIONS(17),
    [anon_sym_bool] = ACTIONS(19),
    [anon_sym_byte] = ACTIONS(19),
    [anon_sym_char] = ACTIONS(19),
    [aux_sym_primitive_type_token1] = ACTIONS(19),
    [aux_sym_primitive_type_token2] = ACTIONS(19),
    [anon_sym_duration] = ACTIONS(19),
    [anon_sym_time] = ACTIONS(19),
    [aux_sym_string_type_token1] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_POUND] = ACTIONS(3),
    [aux_sym_string_token1] = ACTIONS(23),
    [aux_sym_string_token2] = ACTIONS(23),
    [sym__decimal_integer] = ACTIONS(25),
    [sym__binary_integer] = ACTIONS(27),
    [sym__hexadecimal_integer] = ACTIONS(27),
    [sym__octal_integer] = ACTIONS(27),
    [aux_sym_float_token1] = ACTIONS(29),
    [aux_sym_float_token2] = ACTIONS(29),
    [anon_sym_True] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_False] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_separator,
    STATE(3), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [56] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_separator,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [112] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_separator,
    STATE(5), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [168] = 14,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      sym_custom_type,
    ACTIONS(50), 1,
      sym_package_specifier,
    ACTIONS(56), 1,
      aux_sym_string_type_token1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(6), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(53), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [220] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym_separator,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [276] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_separator,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [332] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [385] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [438] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [491] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [544] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [597] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(14), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [650] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_source_file_repeat1,
    STATE(15), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [703] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_custom_type,
    ACTIONS(11), 1,
      sym_package_specifier,
    ACTIONS(15), 1,
      aux_sym_string_type_token1,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 1,
      sym_comment,
    STATE(26), 1,
      sym__statement,
    STATE(41), 1,
      sym__base_type,
    STATE(42), 1,
      sym_string_type,
    STATE(43), 1,
      sym_primitive_type,
    STATE(48), 1,
      sym_external_custom_type,
    STATE(55), 1,
      sym__type,
    STATE(32), 2,
      sym_field,
      sym_constant,
    ACTIONS(13), 7,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
  [756] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    ACTIONS(85), 1,
      sym__decimal_integer,
    STATE(17), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_array_value_repeat1,
    STATE(45), 1,
      sym_primitive_value,
    ACTIONS(23), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(87), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
    ACTIONS(89), 4,
      anon_sym_True,
      anon_sym_true,
      anon_sym_False,
      anon_sym_false,
    STATE(24), 4,
      sym_string,
      sym_integer,
      sym_float,
      sym_bool,
  [800] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym__decimal_integer,
    STATE(18), 1,
      sym_comment,
    STATE(19), 1,
      aux_sym_array_value_repeat1,
    STATE(46), 1,
      sym_primitive_value,
    ACTIONS(23), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(87), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
    ACTIONS(89), 4,
      anon_sym_True,
      anon_sym_true,
      anon_sym_False,
      anon_sym_false,
    STATE(24), 4,
      sym_string,
      sym_integer,
      sym_float,
      sym_bool,
  [841] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      sym__decimal_integer,
    STATE(61), 1,
      sym_primitive_value,
    ACTIONS(91), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(100), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    STATE(19), 2,
      sym_comment,
      aux_sym_array_value_repeat1,
    ACTIONS(97), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
    ACTIONS(103), 4,
      anon_sym_True,
      anon_sym_true,
      anon_sym_False,
      anon_sym_false,
    STATE(24), 4,
      sym_string,
      sym_integer,
      sym_float,
      sym_bool,
  [880] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym__decimal_integer,
    STATE(20), 1,
      sym_comment,
    STATE(33), 1,
      sym_primitive_value,
    ACTIONS(23), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(27), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
    ACTIONS(89), 4,
      anon_sym_True,
      anon_sym_true,
      anon_sym_False,
      anon_sym_false,
    STATE(24), 4,
      sym_string,
      sym_integer,
      sym_float,
      sym_bool,
  [918] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(108), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [943] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(110), 6,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(112), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [968] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(114), 6,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(116), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [993] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_comment,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(120), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1018] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(124), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1041] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(128), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1064] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(132), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1087] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(136), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1110] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_comment,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(140), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1133] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(144), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1156] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(148), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1179] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(152), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1202] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(33), 1,
      sym_comment,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(156), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1225] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(160), 1,
      sym__decimal_integer,
    STATE(34), 1,
      sym_comment,
    ACTIONS(158), 11,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_True,
      anon_sym_true,
      anon_sym_False,
      anon_sym_false,
  [1248] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(35), 1,
      sym_comment,
    ACTIONS(162), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_custom_type,
      sym_package_specifier,
    ACTIONS(164), 8,
      anon_sym_bool,
      anon_sym_byte,
      anon_sym_char,
      aux_sym_primitive_type_token1,
      aux_sym_primitive_type_token2,
      anon_sym_duration,
      anon_sym_time,
      aux_sym_string_type_token1,
  [1271] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym__decimal_integer,
    ACTIONS(166), 1,
      anon_sym_LT_EQ,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      sym_comment,
    STATE(51), 1,
      sym_integer,
    ACTIONS(87), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
  [1295] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      sym_const_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1309] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym__decimal_integer,
    STATE(38), 1,
      sym_comment,
    STATE(59), 1,
      sym_integer,
    ACTIONS(87), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
  [1327] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym__decimal_integer,
    STATE(39), 1,
      sym_comment,
    STATE(44), 1,
      sym_integer,
    ACTIONS(87), 3,
      sym__binary_integer,
      sym__hexadecimal_integer,
      sym__octal_integer,
  [1345] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      anon_sym_LT_EQ,
    STATE(40), 1,
      sym_comment,
    ACTIONS(170), 3,
      sym_identifier,
      sym_const_identifier,
      anon_sym_LBRACK,
  [1360] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_comment,
    STATE(50), 1,
      sym_array,
  [1376] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(178), 3,
      sym_identifier,
      sym_const_identifier,
      anon_sym_LBRACK,
  [1388] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(182), 1,
      sym_const_identifier,
    STATE(43), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_identifier,
      anon_sym_LBRACK,
  [1402] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    ACTIONS(184), 3,
      sym_identifier,
      sym_const_identifier,
      anon_sym_LBRACK,
  [1414] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      sym_comment,
  [1427] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_comment,
  [1440] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(47), 1,
      sym_comment,
    ACTIONS(192), 2,
      sym_identifier,
      anon_sym_LBRACK,
  [1451] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(48), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_identifier,
      anon_sym_LBRACK,
  [1462] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(194), 1,
      sym_custom_type,
    STATE(49), 1,
      sym_comment,
  [1472] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(50), 1,
      sym_comment,
  [1482] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      sym_comment,
  [1492] = 3,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      aux_sym_comment_token1,
    STATE(52), 1,
      sym_comment,
  [1502] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(204), 1,
      anon_sym_EQ,
    STATE(53), 1,
      sym_comment,
  [1512] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      sym_comment,
  [1522] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(55), 1,
      sym_comment,
  [1532] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_comment,
  [1542] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(212), 1,
      sym_identifier,
    STATE(57), 1,
      sym_comment,
  [1552] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [1562] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(216), 1,
      anon_sym_RBRACK,
    STATE(59), 1,
      sym_comment,
  [1572] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(218), 1,
      sym_identifier,
    STATE(60), 1,
      sym_comment,
  [1582] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      sym_comment,
  [1592] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 332,
  [SMALL_STATE(10)] = 385,
  [SMALL_STATE(11)] = 438,
  [SMALL_STATE(12)] = 491,
  [SMALL_STATE(13)] = 544,
  [SMALL_STATE(14)] = 597,
  [SMALL_STATE(15)] = 650,
  [SMALL_STATE(16)] = 703,
  [SMALL_STATE(17)] = 756,
  [SMALL_STATE(18)] = 800,
  [SMALL_STATE(19)] = 841,
  [SMALL_STATE(20)] = 880,
  [SMALL_STATE(21)] = 918,
  [SMALL_STATE(22)] = 943,
  [SMALL_STATE(23)] = 968,
  [SMALL_STATE(24)] = 993,
  [SMALL_STATE(25)] = 1018,
  [SMALL_STATE(26)] = 1041,
  [SMALL_STATE(27)] = 1064,
  [SMALL_STATE(28)] = 1087,
  [SMALL_STATE(29)] = 1110,
  [SMALL_STATE(30)] = 1133,
  [SMALL_STATE(31)] = 1156,
  [SMALL_STATE(32)] = 1179,
  [SMALL_STATE(33)] = 1202,
  [SMALL_STATE(34)] = 1225,
  [SMALL_STATE(35)] = 1248,
  [SMALL_STATE(36)] = 1271,
  [SMALL_STATE(37)] = 1295,
  [SMALL_STATE(38)] = 1309,
  [SMALL_STATE(39)] = 1327,
  [SMALL_STATE(40)] = 1345,
  [SMALL_STATE(41)] = 1360,
  [SMALL_STATE(42)] = 1376,
  [SMALL_STATE(43)] = 1388,
  [SMALL_STATE(44)] = 1402,
  [SMALL_STATE(45)] = 1414,
  [SMALL_STATE(46)] = 1427,
  [SMALL_STATE(47)] = 1440,
  [SMALL_STATE(48)] = 1451,
  [SMALL_STATE(49)] = 1462,
  [SMALL_STATE(50)] = 1472,
  [SMALL_STATE(51)] = 1482,
  [SMALL_STATE(52)] = 1492,
  [SMALL_STATE(53)] = 1502,
  [SMALL_STATE(54)] = 1512,
  [SMALL_STATE(55)] = 1522,
  [SMALL_STATE(56)] = 1532,
  [SMALL_STATE(57)] = 1542,
  [SMALL_STATE(58)] = 1552,
  [SMALL_STATE(59)] = 1562,
  [SMALL_STATE(60)] = 1572,
  [SMALL_STATE(61)] = 1582,
  [SMALL_STATE(62)] = 1592,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 2, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 2, 0, 4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 3, 0, 9),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 5, 0, 14),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3, 0, 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 4, 0, 10),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 4, 0, 12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3, 0, 8),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 4, 0, 13),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_value, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_value, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 7),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 7),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_default, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_default, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 4, 0, 11),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 4, 0, 11),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_value_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_type, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base_type, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_type, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_custom_type, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [210] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ros_interface(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ros_interface",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
